language: ruby
os: linux
dist: trusty
rvm:
- 2.4.1
install: gem install jekyll -v 3.8.0 && gem install jekyll-redirect-from && gem install
  s3_website
script: jekyll build
after_success:
- test $TRAVIS_BRANCH = "master" && s3_website push --config-dir=_config/production/
- test $TRAVIS_BRANCH = "staging" && s3_website push --config-dir=_config/staging/
branches:
  only:
  - master
  - staging
notifications:
  slack:
    rooms:
      secure: NPR/xQM8lXlPLX3mWakM/Kqsk1NBgRRo2KksYSUBUD4BS7YndoeRAFaT45pmMnwoEwjotBrkc4GT53l5nf1QECZ+tDTGYF/KSXpsVWfzfB4BRM7kklbMkftF5qf3WR1y1s70/XYCDZyfWYqkSslxKw4tZt49+QQYcgQvfFxKrknr0w8u73TNgU7TvRB8nsm9zrxpgNVhR1ZFGzQsIUUIqhlkH3+5IWcBQXs/pYoT4YP3Y+aLjLUILsIr8BbDR766L9aUpxN5IibwKPwHuu98QGJwoa2VZrcqXGiI5no/tjaPmM7Gq+PbMgnXLyTb1fkaQsNmjBzGjGril+z4PERiCmufURtTt40QC/yOa/a1/z7N7DJifPUcvsJio9bf2Lvcj5Nwn+dy7IzJxZ4bm7NQwwIgrJ+4DIdP5rPkyHkyjUlZEZPLIATC3I4TdwXwLE+kIBthM03xnXDMdkBbyIwWf5nksGryPddOIbUhF1dj/qbA97cLBuiJIhW0DZk0wwNbPyLcCcN2H+lIX+0NLoyO3cloQCvJk4d9HGiXjtiCnaHemiWuaH+vJoIrggu1tXvMHvlGkZKr0QtWGLQ/Ms2qrhjblSzap8t/bC4H1pj/fcD55Kd5xm/GQDiAc2llCrg/zzwQrOSrIiQ3Nqk+8wrjNWnkeWRRTyyndYy/uqi4jPQ=
